### ISSUE TITLE
Allegro support can be possible？

### ISSUE THREAD

**Issue by Hongyu-yu** [svandenhaute/psiflow#1]
Very Interesting work!
Wondering if it can be integrated with Allegro network?
Thanks!

**Comment by svandenhaute** [comment]
Definitely! I'm planning to add support for Allegro and MACE in the coming weeks -- although there are some other features that receive priority for now. However, given the fact that Allegro is effectively just an extension to NequIP, I actually think you can combine an Allegro-enabled config yaml with the existing `NequIPModel` implementation!

If it does not end up working, let me know and I'll take a closer look.

**Comment by Hongyu-yu** [comment]
@svandenhaute Sounds great! Can't wait to have a try! Are there any instructions for user or I should wait for some time? Thanks!

**Comment by svandenhaute** [comment]
Awesome, looking forward to your feedback.
Yes, I'm currently still working on getting the documentation set up with some basic examples included. Within the next week or so, you should be able to get started!

**Comment by Hongyu-yu** [comment]
Wow that's great:) Thank you!

**Comment by svandenhaute** [comment]
@Hongyu-yu I've implemented Allegro as a separate model in psiflow. It is rather picky in terms of torch compatibility (essentially requiring `1.11.0`) which makes is mutually exclusive with MACE as that requires `torch==1.12.1` or later.
In any case; I've started working on the documentation, and the [examples](/svandenhaute/psiflow/tree/master/examples) have been streamlined as well. Do not hesitate to report back any problems -- psiflow is still in development and feedback is extremely important at this stage.

**Comment by Hongyu-yu** [comment]
@svandenhaute Hi, thanks for the update. For the torch compatibility, I only use Allegro so it should be good. I will try to run the examples and give feedback:) Thanks for your work!

**Comment by Hongyu-yu** [comment]
Hi, @svandenhaute
I have been trying to use psiflow recently and during the installation, I meet an issue with ase. For ase of 3.22.1, it goes wrong with 
```
from ase.calculators.calculator import BaseCalculator
```
After updating ase of the latest version from https://github.com/rosswhitfield/ase, it works well.
May you check the version of ase that should be right?

Also, as a user of VASP, examples with vasp will help a lot if provided. Thanks! 

BTW, congratulations to your new publication of psiflow in npj :)

**Comment by svandenhaute** [comment]
I am anticipating ASE 3.23.0, in which they renamed `Calculator` to `BaseCalculator`. If you install the latest version from the ASE gitlab repository, you won't experience that error. In any case, I'll ensure psiflow also works with 3.22.1, the latest version on pypi.

We still have to write the VASP interface. Would you need it soon?

**Comment by Hongyu-yu** [comment]
Yes. It will be convenient for me to do with VASP interface.

**Comment by svandenhaute** [comment]
> Hi, @svandenhaute I have been trying to use psiflow recently and during the installation, I meet an issue with ase. For ase of 3.22.1, it goes wrong with
> 
> ```
> from ase.calculators.calculator import BaseCalculator
> ```
> 
> After updating ase of the latest version from https://github.com/rosswhitfield/ase, it works well. May you check the version of ase that should be right?

This has now been fixed.


> Yes. It will be convenient for me to do with VASP interface.

This is technically low-priority, but we will try to get it done in the coming weeks!

**Comment by Hongyu-yu** [comment]
> This is technically low-priority, but we will try to get it done in the coming weeks!

Thanks!

**Comment by svandenhaute** [comment]
Closing this as completed since Allegro is now officially supported. See #3 for tracking progress on the VASP interface
